"""Создать таблицу books

Revision ID: dd741fc047e0
Revises: 3f65820713fd
Create Date: 2025-11-11 13:22:52.234421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd741fc047e0'
down_revision: Union[str, Sequence[str], None] = '3f65820713fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('year_publication', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('number_pages', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('accessibility', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('number_pages <= 50000', name='check_pages_max'),
    sa.CheckConstraint('number_pages > 0', name='check_pages_positive'),
    sa.CheckConstraint('year_publication <= 2100', name='check_year_max'),
    sa.CheckConstraint('year_publication >= 1000', name='check_year_min'),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index('idx_accessibility', 'books', ['accessibility'], unique=False)
    op.create_index('idx_author_title', 'books', ['author', 'title'], unique=False)
    op.create_index('idx_genre_year', 'books', ['genre', 'year_publication'], unique=False)
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    op.drop_index(op.f('ix_Books_book_id'), table_name='Books')
    op.drop_table('Books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('book_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year_publication', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_pages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accessibility', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('book_id', name=op.f('Books_pkey'))
    )
    op.create_index(op.f('ix_Books_book_id'), 'Books', ['book_id'], unique=False)
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_index('idx_genre_year', table_name='books')
    op.drop_index('idx_author_title', table_name='books')
    op.drop_index('idx_accessibility', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
